# Generated by Django 4.0.10 on 2023-06-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Высота')),
                ('width', models.PositiveIntegerField(blank=True, null=True, verbose_name='Ширина')),
                ('color', models.CharField(blank=True, max_length=64, verbose_name='Цвет')),
            ],
        ),
        migrations.CreateModel(
            name='furniture_types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=64, verbose_name='Типы мебели')),
            ],
        ),
    ]
