# Generated by Django 4.0.10 on 2023-06-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_furniture_price_furniture_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='image',
            field=models.ImageField(blank=True, upload_to='furniture_images'),
        ),
    ]
